# Do not modify this file!  It was generated by ‘nixos-generate-config’ and may be overwritten by future invocations.  Please make changes to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  config = {
    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/dd6c3f65-3605-48e2-9eb4-ecd1b96432ce";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/0955-AA13";
        fsType = "vfat";
      };

    fileSystems."/mnt/old_root" =
      { device = "/dev/disk/by-uuid/30328db0-a23e-44e0-b229-a0601e831a03";
        fsType = "btrfs";
      };

    fileSystems."/srv/media" =
      { device = "/mnt/old_root/srv/media";
        options = [ "bind" ];
      };

    fileSystems."/srv/recordings" =
      { device = "/mnt/old_root/srv/recordings";
        options = [ "bind" ];
      };

    swapDevices = [
       { device = "/dev/disk/by-uuid/8b0a620d-deb5-43ed-9ddb-1c69cfdca247"; }
    ];

    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
