# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2543aacb-746c-46d0-bee4-2a4a3176fd5e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ec992216-7488-449b-b1b3-37d6a8ef17d6".device = "/dev/disk/by-uuid/ec992216-7488-449b-b1b3-37d6a8ef17d6";
  boot.initrd.luks.devices."luks-0959dacc-567e-4b04-8ecb-3363d33eac87".device = "/dev/disk/by-uuid/0959dacc-567e-4b04-8ecb-3363d33eac87";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/89E5-D84F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-0959dacc-567e-4b04-8ecb-3363d33eac87"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
